CREATE TABLE "registrations" (
	"id" serial PRIMARY KEY,
	"full_name" text NOT NULL,
	"email" text,
	"phone" text NOT NULL,
	"whatsapp" text,
	"gender" text,
	"age_group" text,
	"church" text,
	"church_location" text,
	"county" text,
	"ticket_type" text NOT NULL,
	"prayer_request" text,
	"instagram" text,
	"tiktok" text,
	"member2" text,
	"member2_phone" text,
	"member3" text,
	"member3_phone" text,
	"member4" text,
	"member4_phone" text,
	"member5" text,
	"member5_phone" text,
	"event" text DEFAULT 'Breaking the Ice 2026' NOT NULL,
	"till_number" text DEFAULT '216445' NOT NULL,
	"registered_at" timestamp DEFAULT now() NOT NULL
);
