import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

export const registrations = pgTable("registrations", {
  id: serial().primaryKey(),
  fullName: text("full_name").notNull(),
  email: text("email"),
  phone: text("phone").notNull(),
  whatsapp: text("whatsapp"),
  gender: text("gender"),
  ageGroup: text("age_group"),
  church: text("church"),
  churchLocation: text("church_location"),
  county: text("county"),
  ticketType: text("ticket_type").notNull(),
  prayerRequest: text("prayer_request"),
  instagram: text("instagram"),
  tiktok: text("tiktok"),
  member2: text("member2"),
  member2Phone: text("member2_phone"),
  member3: text("member3"),
  member3Phone: text("member3_phone"),
  member4: text("member4"),
  member4Phone: text("member4_phone"),
  member5: text("member5"),
  member5Phone: text("member5_phone"),
  event: text("event").notNull().default("Breaking the Ice 2026"),
  tillNumber: text("till_number").notNull().default("216445"),
  registeredAt: timestamp("registered_at").defaultNow().notNull(),
});
